name: Analisis Libreria
description: File a bug report.
title: "Problema en la librería: [Indica aquí]"  # Título por defecto o con instrucciones
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]  # Asegúrate de que los proyectos existan
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo para llenar este reporte de error.

  - type: input
    id: contacto
    attributes:
      label: Detalles de contacto
      description: ¿Cómo podemos ponernos en contacto con usted si necesitamos más información?
      placeholder: ex.
