name: Analisis Libreria
description: File a bug report.
title:
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contaco
    attributes:
      label: Detalles de contacto
      description: ¿Cómo podemos ponernos en contacto con usted si necesitamos más información?
      placeholder: ex. email@example.co
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Cual es tu solicitud?
      description: Cuentanos que necesitas
      placeholder: Debes indicar las coordenadas de la libreria
      value: 
    validations:
      required: true
    validations:
      required: true
  - type: textarea
    id: logs
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
