name: Solicitud analisis libreria de terceros
about: Realizar el analisis de librerias
title: ''
labels: ''
assignees: ''

body:

  - type: input
    id: contacto
    attributes:
      label: Detalles de contacto
      description: ¿Cómo podemos ponernos en contacto con usted si necesitamos más información?
      placeholder: ex. email@example.com
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Cuál es tu solicitud?
      description: Cuéntanos qué necesitas
      placeholder: Detalles solicitud
    validations:
      required: true

  - type: textarea
    id: what-coordenate
    attributes:
      label: Detalle libreria
      description:  Debes indicar la oordenada de la libreria.
      placeholder: "example: npm:file-saver:file-saver:2.0.1"
    validations:
      required: true    
      
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conducta
      description: Al enviar este issue, aceptas seguir nuestro [Código de Conducta](https://example.com).
      options:
        - label: Acepto seguir el Código de Conducta de este proyecto
          required: true
